services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: apps/nextjs/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
      - AUTH_SECRET=supersecret
      - AUTH_DISCORD_ID=${AUTH_DISCORD_ID}
      - AUTH_DISCORD_SECRET=${AUTH_DISCORD_SECRET}
      - AUTH_TRUST_HOST=true

  db:
    container_name: postgresdb
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgresdb-data:/var/lib/postgresql/data

volumes:
  postgresdb-data:
    driver: local
